#!/usr/bin/env bash
set -x
set -e

/sbin/resize2fs /dev/mmcblk0p1
/usr/bin/qdbus --system org.freedesktop.Accounts /org/freedesktop/Accounts org.freedesktop.Accounts.DeleteUser 1000 true
/usr/bin/pkcon -y remove calamares c1-calamares-core
